version: '3.7'

networks:
  default:
    external: true
    name: gravitee-redpanda

services:
  redpanda:
    # NOTE: Use the latest version here!
    image: docker.redpanda.com/vectorized/redpanda:latest
    container_name: redpanda-1
    command:
    - redpanda
    - start
    - --smp
    - '1'
    - --reserve-memory
    - 0M
    - --overprovisioned
    - --set redpanda.empty_seed_starts_cluster=false
    - --seeds "redpanda-1:33145"
    - --kafka-addr
    - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
    - --advertise-kafka-addr
    - PLAINTEXT://redpanda:29092,OUTSIDE://3.223.129.198:9092
    - --pandaproxy-addr
    - PLAINTEXT://0.0.0.0:28082,OUTSIDE://0.0.0.0:8086
    - --advertise-pandaproxy-addr
    - PLAINTEXT://redpanda:28082,OUTSIDE://3.223.129.198:8086
    - --advertise-rpc-addr redpanda-1:33145
    ports:
    - 8081:8081
    - 8086:8086
    - 9092:9092
    - 28082:28082
    - 29092:29092
